# Dockerfile for MySQL
#FROM mysql:latest

# Environment variables
#ENV MYSQL_ROOT_PASSWORD=shivchoudhary123
#ENV MYSQL_DATABASE=employee_system
#ENV MYSQL_USER=root
#ENV MYSQL_PASSWORD=shivchoudhary123

# Expose port
#EXPOSE 3306
